import type { Metadata } from "next";

import "./globals.css"
import { Poppins } from 'next/font/google';
import { Plus_Jakarta_Sans } from 'next/font/google';

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Include what you need
  variable: '--font-plusjakarta',
}); 

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Add the weights you need
  variable: '--font-poppins', // This allows using it via Tailwind
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} ${plusJakarta.variable} bg-black antialiased`}
      >
        
        {children}
     
      </body>
    </html>
  );
}
